In [3]:
import pandas as pd

# Base city list (starter set across US; we will expand automatically)
# These are common examples; we will programmatically expand to 300+ cities soon.
cities = [
    "Atlanta, GA", "Charlotte, NC", "Raleigh, NC", "Durham, NC",
    "Houston, TX", "Dallas, TX", "New Orleans, LA", "Birmingham, AL",
    "Richmond, VA", "Washington, DC", "Baltimore, MD",
    "Orlando, FL", "Tampa, FL", "Miami, FL",
    "Nashville, TN", "Memphis, TN", "Louisville, KY",
    "Cincinnati, OH", "Columbus, OH",
    "Chicago, IL", "Detroit, MI", "Cleveland, OH", "Toledo, OH",
    "Phoenix, AZ", "Tucson, AZ",
    "Los Angeles, CA", "San Diego, CA", "San Francisco, CA", "Oakland, CA",
    "Seattle, WA", "Portland, OR",
    "Denver, CO", "Colorado Springs, CO"
]

df = pd.DataFrame({"city": cities})
df

                    city
0            Atlanta, GA
1          Charlotte, NC
2            Raleigh, NC
3             Durham, NC
4            Houston, TX
5             Dallas, TX
6        New Orleans, LA
7         Birmingham, AL
8           Richmond, VA
9         Washington, DC
10         Baltimore, MD
11           Orlando, FL
12             Tampa, FL
13             Miami, FL
14         Nashville, TN
15           Memphis, TN
16        Louisville, KY
17        Cincinnati, OH
18          Columbus, OH
19           Chicago, IL
20           Detroit, MI
21         Cleveland, OH
22            Toledo, OH
23           Phoenix, AZ
24            Tucson, AZ
25       Los Angeles, CA
26         San Diego, CA
27     San Francisco, CA
28           Oakland, CA
29           Seattle, WA
30          Portland, OR
31            Denver, CO
32  Colorado Springs, CO

In [4]:
!pip install requests uszipcode openmeteo_requests pandas numpy

Requirement already satisfied: requests in ./venv/lib/python3.12/site-packages (2.32.5)
Collecting uszipcode
  Downloading uszipcode-1.0.1-py2.py3-none-any.whl.metadata (8.9 kB)
Collecting openmeteo_requests
  Downloading openmeteo_requests-1.7.4-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: pandas in ./venv/lib/python3.12/site-packages (2.3.3)
Requirement already satisfied: numpy in ./venv/lib/python3.12/site-packages (2.3.4)
Requirement already satisfied: charset_normalizer<4,>=2 in ./venv/lib/python3.12/site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in ./venv/lib/python3.12/site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./venv/lib/python3.12/site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.12/site-packages (from requests) (2025.10.5)
Requirement already satisfied: attrs in ./venv/lib/python3.12/site-packages (from uszipcode) (25.4.0)
Collecting pathlib-mate (from uszipcode)
  Downloading pathlib_mate-1.3.2-py3-none-any.whl.metadata (8.4 kB)
Collecting atomicwrites (from uszipcode)
  Downloading atomicwrites-1.4.1.tar.gz (14 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting fuzzywuzzy (from uszipcode)
  Downloading fuzzywuzzy-0.18.0-py2.py3-none-any.whl.metadata (4.9 kB)
Collecting haversine>=2.5.0 (from uszipcode)
  Downloading haversine-2.9.0-py2.py3-none-any.whl.metadata (5.8 kB)
Collecting SQLAlchemy>=1.4.0 (from uszipcode)
  Downloading sqlalchemy-2.0.44-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.5 kB)
Collecting sqlalchemy-mate>=1.4.28.3 (from uszipcode)
  Downloading sqlalchemy_mate-2.0.0.3-py3-none-any.whl.metadata (11 kB)
Collecting niquests>=3.15.2 (from openmeteo_requests)
  Downloading niquests-3.15.2-py3-none-any.whl.metadata (16 kB)
Collecting openmeteo-sdk>=1.22.0 (from openmeteo_requests)
  Downloading openmeteo_sdk-1.22.0-py3-none-any.whl.metadata (935 bytes)
Requirement already satisfied: python-dateutil>=2.8.2 in ./venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./venv/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in ./venv/lib/python3.12/site-packages (from pandas) (2025.2)
Collecting urllib3-future<3,>=2.13.903 (from niquests>=3.15.2->openmeteo_requests)
  Downloading urllib3_future-2.14.906-py3-none-any.whl.metadata (16 kB)
Collecting wassima<3,>=1.0.1 (from niquests>=3.15.2->openmeteo_requests)
  Downloading wassima-2.0.2-py3-none-any.whl.metadata (3.7 kB)
Collecting flatbuffers==25.9.23 (from openmeteo-sdk>=1.22.0->openmeteo_requests)
  Downloading flatbuffers-25.9.23-py2.py3-none-any.whl.metadata (875 bytes)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Collecting greenlet>=1 (from SQLAlchemy>=1.4.0->uszipcode)
  Downloading greenlet-3.2.4-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (4.1 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in ./venv/lib/python3.12/site-packages (from SQLAlchemy>=1.4.0->uszipcode) (4.15.0)
Collecting prettytable<4.0.0,>=3.0.0 (from sqlalchemy-mate>=1.4.28.3->uszipcode)
  Downloading prettytable-3.16.0-py3-none-any.whl.metadata (33 kB)
Requirement already satisfied: wcwidth in ./venv/lib/python3.12/site-packages (from prettytable<4.0.0,>=3.0.0->sqlalchemy-mate>=1.4.28.3->uszipcode) (0.2.14)
Requirement already satisfied: h11<1.0.0,>=0.11.0 in ./venv/lib/python3.12/site-packages (from urllib3-future<3,>=2.13.903->niquests>=3.15.2->openmeteo_requests) (0.16.0)
Collecting jh2<6.0.0,>=5.0.3 (from urllib3-future<3,>=2.13.903->niquests>=3.15.2->openmeteo_requests)
  Downloading jh2-5.0.10-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.0 kB)
Collecting qh3<2.0.0,>=1.5.4 (from urllib3-future<3,>=2.13.903->niquests>=3.15.2->openmeteo_requests)
  Downloading qh3-1.5.5-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.8 kB)
Downloading uszipcode-1.0.1-py2.py3-none-any.whl (35 kB)
Downloading openmeteo_requests-1.7.4-py3-none-any.whl (7.0 kB)
Downloading haversine-2.9.0-py2.py3-none-any.whl (7.7 kB)
Downloading niquests-3.15.2-py3-none-any.whl (167 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 167.1/167.1 kB 14.8 MB/s eta 0:00:00
Downloading openmeteo_sdk-1.22.0-py3-none-any.whl (18 kB)
Downloading flatbuffers-25.9.23-py2.py3-none-any.whl (30 kB)
Downloading sqlalchemy-2.0.44-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 102.8 MB/s eta 0:00:00
Downloading sqlalchemy_mate-2.0.0.3-py3-none-any.whl (59 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.9/59.9 kB 5.4 MB/s eta 0:00:00
Downloading fuzzywuzzy-0.18.0-py2.py3-none-any.whl (18 kB)
Downloading pathlib_mate-1.3.2-py3-none-any.whl (56 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.0/57.0 kB 5.1 MB/s eta 0:00:00
Downloading greenlet-3.2.4-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (607 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 607.6/607.6 kB 40.6 MB/s eta 0:00:00
Downloading prettytable-3.16.0-py3-none-any.whl (33 kB)
Downloading urllib3_future-2.14.906-py3-none-any.whl (683 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 684.0/684.0 kB 46.4 MB/s eta 0:00:00
Downloading wassima-2.0.2-py3-none-any.whl (145 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 145.8/145.8 kB 13.2 MB/s eta 0:00:00
Downloading jh2-5.0.10-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (394 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 394.1/394.1 kB 29.5 MB/s eta 0:00:00
Downloading qh3-1.5.5-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 92.5 MB/s eta 0:00:00
Building wheels for collected packages: atomicwrites
  Building wheel for atomicwrites (pyproject.toml) ... done
  Created wheel for atomicwrites: filename=atomicwrites-1.4.1-py2.py3-none-any.whl size=7020 sha256=6ffd21f92c54b062889d5785165bfd63034436ab335f6522b032579a692f0a70
  Stored in directory: /home/ubuntu/.cache/pip/wheels/6b/37/a4/ae30755673c2d1e07228f13b4491fcaef62438f771d5012d07
Successfully built atomicwrites
Installing collected packages: fuzzywuzzy, flatbuffers, wassima, qh3, prettytable, pathlib-mate, openmeteo-sdk, jh2, haversine, greenlet, atomicwrites, urllib3-future, SQLAlchemy, sqlalchemy-mate, niquests, uszipcode, openmeteo_requests
Successfully installed SQLAlchemy-2.0.44 atomicwrites-1.4.1 flatbuffers-25.9.23 fuzzywuzzy-0.18.0 greenlet-3.2.4 haversine-2.9.0 jh2-5.0.10 niquests-3.15.2 openmeteo-sdk-1.22.0 openmeteo_requests-1.7.4 pathlib-mate-1.3.2 prettytable-3.16.0 qh3-1.5.5 sqlalchemy-mate-2.0.0.3 urllib3-future-2.14.906 uszipcode-1.0.1 wassima-2.0.2

In [5]:
import requests
import time

def fetch_numbeo(city):
    """Fetch cost of living & crime for a city using Numbeo API scrape."""
    url = f"https://www.numbeo.com/api/city_prices?api_key=YOUR_KEY&query={city}"
    return requests.get(url).json() if "YOUR_KEY" not in url else {}

data = []

for c in df["city"]:
    print("Fetching:", c)
    # (placeholder metrics until API key added)
    data.append({
        "city": c,
        "cost_index": None,
        "rent_1br": None,
        "crime_index": None,
    })
    time.sleep(1)

city_stats = pd.DataFrame(data)
city_stats

Fetching: Atlanta, GA
Fetching: Charlotte, NC
Fetching: Raleigh, NC
Fetching: Durham, NC
Fetching: Houston, TX
Fetching: Dallas, TX
Fetching: New Orleans, LA
Fetching: Birmingham, AL
Fetching: Richmond, VA
Fetching: Washington, DC
Fetching: Baltimore, MD
Fetching: Orlando, FL
Fetching: Tampa, FL
Fetching: Miami, FL
Fetching: Nashville, TN
Fetching: Memphis, TN
Fetching: Louisville, KY
Fetching: Cincinnati, OH
Fetching: Columbus, OH
Fetching: Chicago, IL
Fetching: Detroit, MI
Fetching: Cleveland, OH
Fetching: Toledo, OH
Fetching: Phoenix, AZ
Fetching: Tucson, AZ
Fetching: Los Angeles, CA
Fetching: San Diego, CA
Fetching: San Francisco, CA
Fetching: Oakland, CA
Fetching: Seattle, WA
Fetching: Portland, OR
Fetching: Denver, CO
Fetching: Colorado Springs, CO

                    city cost_index rent_1br crime_index
0            Atlanta, GA       None     None        None
1          Charlotte, NC       None     None        None
2            Raleigh, NC       None     None        None
3             Durham, NC       None     None        None
4            Houston, TX       None     None        None
5             Dallas, TX       None     None        None
6        New Orleans, LA       None     None        None
7         Birmingham, AL       None     None        None
8           Richmond, VA       None     None        None
9         Washington, DC       None     None        None
10         Baltimore, MD       None     None        None
11           Orlando, FL       None     None        None
12             Tampa, FL       None     None        None
13             Miami, FL       None     None        None
14         Nashville, TN       None     None        None
15           Memphis, TN       None     None        None
16        Louisville, KY       None     None        None
17        Cincinnati, OH       None     None        None
18          Columbus, OH       None     None        None
19           Chicago, IL       None     None        None
20           Detroit, MI       None     None        None
21         Cleveland, OH       None     None        None
22            Toledo, OH       None     None        None
23           Phoenix, AZ       None     None        None
24            Tucson, AZ       None     None        None
25       Los Angeles, CA       None     None        None
26         San Diego, CA       None     None        None
27     San Francisco, CA       None     None        None
28           Oakland, CA       None     None        None
29           Seattle, WA       None     None        None
30          Portland, OR       None     None        None
31            Denver, CO       None     None        None
32  Colorado Springs, CO       None     None        None

In [6]:
from openmeteo_requests import Client
import numpy as np

client = Client()

temps = []
for c in df["city"]:
    city_name = c.split(",")[0]
    try:
        resp = client.free(text=city_name)
        temps.append(resp.current.temperature_2m)
    except:
        temps.append(None)

df["avg_temp"] = temps
df

                    city avg_temp
0            Atlanta, GA     None
1          Charlotte, NC     None
2            Raleigh, NC     None
3             Durham, NC     None
4            Houston, TX     None
5             Dallas, TX     None
6        New Orleans, LA     None
7         Birmingham, AL     None
8           Richmond, VA     None
9         Washington, DC     None
10         Baltimore, MD     None
11           Orlando, FL     None
12             Tampa, FL     None
13             Miami, FL     None
14         Nashville, TN     None
15           Memphis, TN     None
16        Louisville, KY     None
17        Cincinnati, OH     None
18          Columbus, OH     None
19           Chicago, IL     None
20           Detroit, MI     None
21         Cleveland, OH     None
22            Toledo, OH     None
23           Phoenix, AZ     None
24            Tucson, AZ     None
25       Los Angeles, CA     None
26         San Diego, CA     None
27     San Francisco, CA     None
28           Oakland, CA     None
29           Seattle, WA     None
30          Portland, OR     None
31            Denver, CO     None
32  Colorado Springs, CO     None

In [8]:
!pip install census us

Collecting census
  Downloading census-0.8.24-py3-none-any.whl.metadata (8.2 kB)
Collecting us
  Downloading us-3.2.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: requests>=1.1.0 in ./venv/lib/python3.12/site-packages (from census) (2.32.5)
Collecting jellyfish (from us)
  Downloading jellyfish-1.2.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (642 bytes)
Requirement already satisfied: charset_normalizer<4,>=2 in ./venv/lib/python3.12/site-packages (from requests>=1.1.0->census) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in ./venv/lib/python3.12/site-packages (from requests>=1.1.0->census) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./venv/lib/python3.12/site-packages (from requests>=1.1.0->census) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.12/site-packages (from requests>=1.1.0->census) (2025.10.5)
Downloading census-0.8.24-py3-none-any.whl (11 kB)
Downloading us-3.2.0-py3-none-any.whl (13 kB)
Downloading jellyfish-1.2.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (360 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 360.5/360.5 kB 15.6 MB/s eta 0:00:00
Installing collected packages: jellyfish, us, census
Successfully installed census-0.8.24 jellyfish-1.2.1 us-3.2.0

In [14]:
from census import Census
from us import states
import pandas as pd

CENSUS_KEY = "7e2aa0723914b4b33da982ed7ef78f11074bd7df"  # replace but do NOT commit to git
c = Census(CENSUS_KEY)

diversity_data = []

for cty in df["city"]:
    name, state = cty.split(", ")
    try:
        pop = c.acs5.table("B03002", state=states.lookup(state).fips, county=None)
    except:
        diversity_data.append(None)
        continue

    # Extract race counts
    record = pop[0]
    # Racial categories used in diversity index
    groups = [
        record["B03002_003E"],  # White alone
        record["B03002_004E"],  # Black/African American alone
        record["B03002_006E"],  # Asian alone
        record["B03002_007E"],  # Native American/Alaska Native alone
        record["B03002_012E"],  # Two or more races
        record["B03002_005E"] + record["B03002_008E"] + record["B03002_009E"]  # Hispanic aggregated
    ]
    
    total = sum(groups)
    p = [x/total for x in groups if x > 0]

    # Shannon Diversity Index
    import numpy as np
    diversity = -sum([x*np.log(x) for x in p])
    diversity_data.append(diversity)

df["diversity_index"] = diversity_data
df

                    city avg_temp diversity_index
0            Atlanta, GA     None            None
1          Charlotte, NC     None            None
2            Raleigh, NC     None            None
3             Durham, NC     None            None
4            Houston, TX     None            None
5             Dallas, TX     None            None
6        New Orleans, LA     None            None
7         Birmingham, AL     None            None
8           Richmond, VA     None            None
9         Washington, DC     None            None
10         Baltimore, MD     None            None
11           Orlando, FL     None            None
12             Tampa, FL     None            None
13             Miami, FL     None            None
14         Nashville, TN     None            None
15           Memphis, TN     None            None
16        Louisville, KY     None            None
17        Cincinnati, OH     None            None
18          Columbus, OH     None            None
19           Chicago, IL     None            None
20           Detroit, MI     None            None
21         Cleveland, OH     None            None
22            Toledo, OH     None            None
23           Phoenix, AZ     None            None
24            Tucson, AZ     None            None
25       Los Angeles, CA     None            None
26         San Diego, CA     None            None
27     San Francisco, CA     None            None
28           Oakland, CA     None            None
29           Seattle, WA     None            None
30          Portland, OR     None            None
31            Denver, CO     None            None
32  Colorado Springs, CO     None            None

In [15]:
pip install "fuzzywuzzy[speedup]"
# or explicitly
pip install python-Levenshtein

SyntaxError: invalid syntax (784481473.py, line 1)