In [1]:
import pandas as pd

data = {
    "city": ["Charlotte", "Raleigh", "Atlanta"],
    "state": ["NC", "NC", "GA"],
    "rent": [1700, 1650, 1800],
    "temperature": [68, 66, 72],
    "diversity_score": [0.81, 0.79, 0.83]
}

df = pd.DataFrame(data)
df.to_csv("cities.csv", index=False)

df

        city state  rent  temperature  diversity_score
0  Charlotte    NC  1700           68             0.81
1    Raleigh    NC  1650           66             0.79
2    Atlanta    GA  1800           72             0.83

In [3]:
df.info()
df.describe()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   city             3 non-null      object
 1   state            3 non-null      object
 2   rent             3 non-null      int64
 3   temperature      3 non-null      int64
 4   diversity_score  3 non-null      float64
dtypes: float64(1), int64(2), object(2)
memory usage: 252.0+ bytes

city               0
state              0
rent               0
temperature        0
diversity_score    0
dtype: int64

In [4]:
def score_city(row, 
               pref_region=['East','South'],
               pref_min_rent=1500,
               pref_max_rent=2500,
               pref_climate=['Mild','Warm'],
               pref_diversity='High',
               pref_lifestyle='Balanced'):

    score = 0

    # Region
    if row['region'] in pref_region:
        score += 20

    # Rent
    if pref_min_rent <= row['rent'] <= pref_max_rent:
        score += 20

    # Climate
    if row['climate'] in pref_climate:
        score += 20

    # Diversity
    if row['diversity'] == pref_diversity:
        score += 20

    # Lifestyle
    if row['lifestyle'] == pref_lifestyle:
        score += 20

    return score

In [6]:
df.columns

Index(['city', 'state', 'rent', 'temperature', 'diversity_score'], dtype='object')

In [7]:
def score_city(row, 
               pref_min_rent, pref_max_rent, 
               pref_min_temp, pref_max_temp,
               pref_diversity):
    
    score = 0
    
    # Rent score
    if pref_min_rent <= row['rent'] <= pref_max_rent:
        score += 30

    # Temperature score
    if pref_min_temp <= row['temperature'] <= pref_max_temp:
        score += 30

    # Diversity score (0–100)
    score += (row['diversity_score'] / 100) * 20

    return score

In [8]:
df['score'] = df.apply(
    lambda row: score_city(
        row,
        pref_min_rent=1500,
        pref_max_rent=2500,
        pref_min_temp=60,
        pref_max_temp=85,
        pref_diversity=60
    ), 
    axis=1
)

df.sort_values('score', ascending=False).head(10)

        city state  rent  temperature  diversity_score   score
2    Atlanta    GA  1800           72             0.83  60.166
0  Charlotte    NC  1700           68             0.81  60.162
1    Raleigh    NC  1650           66             0.79  60.158

In [9]:
df['region'] = 'South'
df['climate'] = 'Warm'
df['lifestyle'] = 'Balanced'

In [10]:
south_states = ['TX', 'FL', 'GA', 'NC', 'SC', 'LA', 'AL', 'TN', 'MS', 'VA']
df['region'] = df['state'].apply(lambda s: 'South' if s in south_states else 'Other')