In [1]:
import pandas as pd

# Start with initial seed cities across East Coast + South
cities = [
    "Atlanta, GA", "Charlotte, NC", "Raleigh, NC", "Durham, NC",
    "Houston, TX", "Dallas, TX", "New Orleans, LA",
    "Richmond, VA", "Washington, DC", "Baltimore, MD",
    "Orlando, FL", "Tampa, FL", "Miami, FL"
]

cities_df = pd.DataFrame({"city": cities})
cities_df

               city
0       Atlanta, GA
1     Charlotte, NC
2       Raleigh, NC
3        Durham, NC
4       Houston, TX
5        Dallas, TX
6   New Orleans, LA
7      Richmond, VA
8    Washington, DC
9     Baltimore, MD
10      Orlando, FL
11        Tampa, FL
12        Miami, FL

In [2]:
import pandas as pd

cities = [
    "Atlanta, GA", "Charlotte, NC", "Raleigh, NC", "Durham, NC",
    "Houston, TX", "Dallas, TX", "New Orleans, LA",
    "Richmond, VA", "Washington, DC", "Baltimore, MD",
    "Orlando, FL", "Tampa, FL", "Miami, FL"
]

df = pd.DataFrame({"city": cities})
df

               city
0       Atlanta, GA
1     Charlotte, NC
2       Raleigh, NC
3        Durham, NC
4       Houston, TX
5        Dallas, TX
6   New Orleans, LA
7      Richmond, VA
8    Washington, DC
9     Baltimore, MD
10      Orlando, FL
11        Tampa, FL
12        Miami, FL